# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2024 Tomas Paukrt

# list of static libraries to be built
STATIC_LIBS := libdemo

# list of programs to be built
PROGRAMS := demo

# build rules
include ../Rules.mk
